set echo on
set verify on

  --- Verify populated COURSE_INFORMATION TABLE---
SELECT * FROM COURSE_INFORMATION;
 
 --- Verify populated TEE_TIMES TABLE---
SELECT * FROM TEE_TIMES;

 --- Verify populated CUSTOMER TABLE---
SELECT * FROM CUSTOMER;

 --- Verify populated CERDIT_CARD TABLE---
SELECT * FROM CREDIT_CARD;

--- Verify populated RESERVATION TABLE ---
SELECT * FROM RESERVATION;

--- Verify populated CUSTOMER_REVIEW TABLE---
SELECT * FROM CUSTOMER_REVIEW;
 
--- Verify populated FOREEVER_REWARDS TABLE---
SELECT * FROM FOREEVER_REWARDS;

--- Verify populated PROMO_CODE TABLE---
SELECT * FROM PROMO_CODE;
 
--- Verify populated CUSTOMER_COURSE_BRIDGE TABLE ---
SELECT * FROM CUSTOMER_COURSE_BRIDGE;

--- Verify populated CREDIT_RESERVATION_BRIDGE TABLE ---
SELECT * FROM CREDIT_RESERVATION_BRIDGE;
